"use client"

import { useState, useMemo } from "react"
import { useTranslations, useLocale } from "next-intl"
import { Input } from "@/components/ui/input"
import { Search, X } from "lucide-react"

interface GlossaryTerm {
  term: string
  termEn?: string
  definition: string
  definitionEn?: string
}

const glossaryTerms: GlossaryTerm[] = [
  { term: "API", definition: "Una API (Interfaz de Programación de Aplicaciones) permite que diferentes sistemas o plataformas se comuniquen entre sí. En blockchain, se usa para conectar wallets, dApps y plataformas como EthicHub.", definitionEn: "An API (Application Programming Interface) allows different systems or platforms to communicate with each other. In blockchain, it is used to connect wallets, dApps and platforms such as EthicHub." },
  { term: "API descentralizada (dAPI)", termEn: "Decentralized API (dAPI)", definition: "Una dAPI es una API descentralizada, es decir, sin un servidor central que controle los datos. Aumenta la transparencia y la seguridad en aplicaciones Web3 y contratos inteligentes.", definitionEn: "A dAPI is a decentralized API, meaning it has no central server controlling the data. It increases transparency and security in Web3 applications and smart contracts." },
  { term: "Airdrop", definition: "Un airdrop es la distribución gratuita de tokens o criptomonedas a una comunidad, generalmente como estrategia de marketing o fidelización. En el mundo DeFi, los airdrops permiten atraer usuarios, recompensar participación o lanzar nuevos proyectos. EthicHub ha utilizado airdrops para incentivar el uso del token ETHIX.", definitionEn: "An airdrop is the free distribution of tokens or cryptocurrencies to a community, usually as a marketing or loyalty strategy. In the DeFi world, airdrops help attract users, reward participation, or launch new projects. EthicHub has used airdrops to incentivize the use of the ETHIX token." },
  { term: "Algoritmo", termEn: "Algorithm", definition: "Un algoritmo es una secuencia de instrucciones lógicas que permiten realizar tareas de forma automática. En blockchain, los algoritmos determinan procesos como el consenso, el staking o la asignación de recompensas.", definitionEn: "An algorithm is a sequence of logical instructions that enable tasks to be carried out automatically. In blockchain, algorithms determine processes such as consensus, staking, or reward distribution." },
  { term: "Altcoin", definition: "Una altcoin es cualquier criptomoneda que no sea Bitcoin. Incluye proyectos como Ethereum, Cardano o DAI. Muchas altcoins tienen usos específicos y tecnología propia.", definitionEn: "An altcoin is any cryptocurrency that is not Bitcoin. It includes projects like Ethereum, Cardano, or DAI. Many altcoins have specific uses and their own underlying technology." },
  { term: "Altseason", definition: "Término que se refiere a un periodo de tiempo donde las altcoins superan el rendimiento de Bitcoin. Es común en ciclos de mercado y genera gran interés entre traders.", definitionEn: "Term that refers to a period of time where altcoins outperform Bitcoin. It is common in market cycles and generates great interest among traders." },
  { term: "Arbitraje", termEn: "Arbitrage", definition: "El arbitraje cripto consiste en aprovechar la diferencia de precio de un mismo activo entre distintos exchanges para obtener beneficio. Es una práctica común en mercados con alta volatilidad.", definitionEn: "Crypto arbitrage consists of taking advantage of price differences for the same asset across different exchanges to make a profit. It is a common practice in markets with high volatility." },
  { term: "Asset", termEn: "Asset", definition: "En cripto, un asset (activo) puede ser una moneda, un token, un NFT o cualquier recurso digital con valor económico. Ethix, por ejemplo, es un impact asset.", definitionEn: "In crypto, an asset can be a coin, a token, an NFT, or any digital asset with economic value. Ethix, for example, is an impact asset." },
  { term: "Auditores", termEn: "Auditors", definition: "Los auditores en blockchain revisan el código y los contratos inteligentes para detectar fallos de seguridad o malas prácticas. Son clave en proyectos DeFi y para generar confianza.", definitionEn: "Blockchain auditors review code and smart contracts to detect security flaws or poor practices. They are essential in DeFi projects and for building trust." },
  { term: "Aval General", termEn: "General Crowd Collateral", definition: "Funciona como un fondo colectivo de respaldo que cubre préstamos en caso de impago, cuando no hay aval específico a un originador. Refuerza la seguridad del ecosistema.", definitionEn: "It works as a collective backup fund that covers loans in case of default when there is no specific collateral for an originator. It strengthens the security of the ecosystem." },
  { term: "Aval a Originador", termEn: "Originator Collateral", definition: "Es un tipo de respaldo específico que los usuarios de EthicHub pueden hacer con ETHIX para cubrir el riesgo de impago de un originador. Este aval genera recompensas por participación en el sistema de confianza.", definitionEn: "It is a type of specific collateral that EthicHub users can provide with ETHIX to cover an originator's default risk. This collateral generates rewards for participating in the trust system." },
  { term: "Avales colectivos", termEn: "Collective guarantees", definition: "Sistema en EthicHub donde varios usuarios avalan préstamos usando ETHIX, creando una red de seguridad para los inversores. Fomenta la descentralización y el compromiso de la comunidad.", definitionEn: "EthicHub system where several users guarantee loans using ETHIX, creating a safety net for investors. It encourages decentralization and community engagement." },
  { term: "Ballena (Whale)", termEn: "Whale", definition: "En cripto, una ballena es una persona o entidad que posee grandes cantidades de un activo digital, y cuya actividad puede influir en el mercado.", definitionEn: "In crypto, a whale is a person or entity that owns large quantities of a digital asset, and whose activity can influence the market." },
  { term: "Big Data", definition: "Conjunto masivo de datos que se analizan con tecnologías avanzadas para descubrir patrones y tomar decisiones. En DeFi se usa para evaluar riesgo, comportamiento y trazabilidad.", definitionEn: "A massive set of data that is analyzed with advanced technologies to discover patterns and make decisions. In DeFi, it is used to evaluate risk, behavior, and traceability." },
  { term: "Bitcoin (mayúscula)", termEn: "Bitcoin (capital letter)", definition: "Es la red descentralizada y el protocolo sobre el cual se ejecuta la criptomoneda bitcoin. Es la primera blockchain pública de la historia.", definitionEn: "It is the decentralized network and protocol on which the bitcoin cryptocurrency runs. It's the first public blockchain in history." },
  { term: "Bitcoin (minúscula)", termEn: "Bitcoin (lowercase)", definition: "Se refiere a la criptomoneda en sí, como unidad de valor (1 bitcoin = 1 BTC). Es útil distinguirlo de \"Bitcoin\" (con mayúscula), que hace referencia a la red.", definitionEn: "It refers to cryptocurrency itself, as a unit of value (1 bitcoin = 1 BTC). It's useful to distinguish it from \"Bitcoin\" (with a capital letter), which refers to the network." },
  { term: "Bitcoin Cash", definition: "Una bifurcación (fork) de Bitcoin surgida en 2017 para permitir transacciones más rápidas y baratas. Tiene su propia comunidad y desarrollo.", definitionEn: "A fork of Bitcoin that emerged in 2017 to allow faster and cheaper transactions. It has its own community and development." },
  { term: "Blockchain", definition: "La blockchain es una tecnología de registro distribuido que almacena información de forma segura, transparente e inmutable. Es la base de criptomonedas, contratos inteligentes y proyectos como EthicHub.", definitionEn: "Blockchain is a distributed ledger technology that stores information in a secure, transparent and immutable way. It is the basis for cryptocurrencies, smart contracts and projects such as EthicHub." },
  { term: "Blockchain Explorer", definition: "Un blockchain explorer es una herramienta que permite consultar todas las transacciones, bloques, wallets y contratos registrados en una blockchain pública. Aporta transparencia y trazabilidad.", definitionEn: "A blockchain explorer is a tool that allows you to check all transactions, blocks, wallets and contracts registered on a public blockchain. It provides transparency and traceability." },
  { term: "Blockchain permisionada", termEn: "Permissioned blockchain", definition: "Una blockchain donde solo ciertos usuarios tienen acceso o permisos para validar transacciones. Se usa en entornos empresariales o institucionales.", definitionEn: "A blockchain where only certain users have access or permissions to validate transactions. It is used in business or institutional environments." },
  { term: "Blockchain pública", termEn: "Public blockchain", definition: "Es una red abierta donde cualquier usuario puede participar, validar transacciones y consultar datos. Ejemplo: Bitcoin, Ethereum, y la blockchain de EthicHub.", definitionEn: "It is an open network where any user can participate, validate transactions and consult data. Example: Bitcoin, Ethereum, and the EthicHub blockchain." },
  { term: "Bloque", termEn: "Block", definition: "Un bloque es una unidad de información que agrupa transacciones dentro de una blockchain. Cada nuevo bloque se añade de forma cronológica, garantizando seguridad e inmutabilidad.", definitionEn: "A block is a unit of information that groups transactions within a blockchain. Each new block is added chronologically, ensuring security and immutability." },
  { term: "Bucle de Incentivos", termEn: "Incentive Loop", definition: "Mecanismo mediante el cual las acciones de los participantes generan recompensas que fortalecen el sistema. En EthicHub, los préstamos y los avales colectivos crean un bucle de incentivos que protege a los inversores y/o avalistas, y beneficia a los agricultores.", definitionEn: "A mechanism through which participants' actions generate rewards that strengthen the system. In EthicHub, loans and collective collateral create an incentive loop that protects investors and/or guarantors and benefits the farmers." },
  { term: "Cadena de suministro", termEn: "Supply chain", definition: "La cadena de suministro representa el recorrido que hace un producto desde su origen hasta el consumidor final. EthicHub mejora la cadena de suministro agrícola con trazabilidad, comercio directo y blockchain.", definitionEn: "The supply chain represents the journey a product takes from its origin to the final consumer. EthicHub improves the agricultural supply chain with traceability, direct trade, and blockchain." },
  { term: "Café Verde", termEn: "Green Coffee", definition: "El café verde es el grano sin tostar, tal como se obtiene tras el procesamiento post-cosecha. Es el producto que se comercializa en origen y que los tostadores compran para transformar.", definitionEn: "Green coffee is the unroasted bean, as it is obtained after post-harvest processing. It is the product traded at origin and purchased by roasters for transformation." },
  { term: "Café de Especialidad", termEn: "Specialty Coffee", definition: "El café de especialidad es aquel que obtiene una puntuación superior a 80 en la escala SCA, destacando por su calidad, origen y trazabilidad. EthicHub trabaja con pequeños caficultores que producen este tipo de café con prácticas sostenibles.", definitionEn: "Specialty coffee is coffee that scores above 80 on the SCA scale, standing out for its quality, origin, and traceability. EthicHub works with small coffee growers who produce this type of coffee using sustainable practices." },
  { term: "Cambio Climático", termEn: "Climate Change", definition: "Fenómeno global causado principalmente por actividades humanas que alteran el clima. EthicHub contribuye a mitigar sus efectos a través de prácticas agrícolas regenerativas y comercio justo.", definitionEn: "A global phenomenon caused mainly by human activities that alter the climate. EthicHub helps mitigate its effects through regenerative agricultural practices and fair trade." },
  { term: "Cartera (Wallet)", termEn: "Wallet", definition: "Una wallet o cartera digital es una herramienta que permite almacenar, enviar y recibir criptomonedas. Puede ser caliente (online) o fría (offline).", definitionEn: "A wallet or digital wallet is a tool that allows you to store, send, and receive cryptocurrencies. It can be hot (online) or cold (offline)." },
  { term: "Clave privada", termEn: "Private Key", definition: "Es la contraseña criptográfica que da acceso total a una wallet. Debe mantenerse en secreto, ya que perderla implica perder los fondos.", definitionEn: "It is the cryptographic password that grants full access to a wallet. It must be kept secret, as losing it means losing the funds." },
  { term: "Clave pública", termEn: "Public Key", definition: "Una clave pública es la dirección que compartes para recibir criptomonedas. Se genera junto con la clave privada, pero no permite el acceso a los fondos.", definitionEn: "A public key is the address you share to receive cryptocurrencies. It is generated together with the private key, but it does not grant access to the funds." },
  { term: "Cold Wallet", definition: "Una cold wallet es una cartera digital que se mantiene desconectada de internet. Ofrece mayor seguridad frente a ataques cibernéticos.", definitionEn: "A cold wallet is a digital wallet kept offline. It provides greater security against cyberattacks." },
  { term: "Comisión de red", termEn: "Network commission", definition: "Es el coste que se paga por realizar una transacción en blockchain. Varía según la red y la congestión del momento.", definitionEn: "It is the cost paid to execute a transaction on a blockchain. It varies depending on the network and current congestion." },
  { term: "Compound (COMP)", definition: "Compound es un protocolo DeFi que permite prestar y pedir prestado criptomonedas. Su token nativo es COMP. Es uno de los pilares del ecosistema de finanzas descentralizadas.", definitionEn: "Compound is a DeFi protocol that allows you to lend and borrow cryptocurrency. Its native token is COMP. It is one of the pillars of the decentralized finance ecosystem." },
  { term: "Contratos inteligentes", termEn: "Smart Contracts", definition: "Son programas autoejecutables almacenados en la blockchain. Permiten crear acuerdos sin intermediarios, con total transparencia y seguridad. EthicHub usa smart contracts para gestionar préstamos agrícolas.", definitionEn: "They are self-executing programs stored on the blockchain. They allow the creation of agreements without intermediaries, with full transparency and security. EthicHub uses smart contracts to manage agricultural loans." },
  { term: "Criptoeuro (EUROChain)", termEn: "Cryptoeuro (EuroChain)", definition: "Proyecto de stablecoin descentralizada ligada al euro. Busca facilitar pagos estables y rápidos en el ecosistema cripto europeo.", definitionEn: "A decentralized stablecoin project pegged to the euro. It aims to facilitate stable and fast payments within the European crypto ecosystem." },
  { term: "Criptomonedas", termEn: "Cryptocurrencies", definition: "Activos digitales que utilizan la criptografía para garantizar transacciones seguras y descentralizadas. Bitcoin, Ethereum y ETHIX son ejemplos de criptomonedas.", definitionEn: "Digital assets that use cryptography to ensure secure and decentralized transactions. Bitcoin, Ethereum, and ETHIX are examples of cryptocurrencies." },
  { term: "Crowdfunding", definition: "Es una forma de financiamiento colectivo donde múltiples personas aportan pequeñas cantidades a un proyecto. EthicHub aplica este modelo en el sector agrícola del café.", definitionEn: "It is a form of collective financing in which multiple people contribute small amounts to a project. EthicHub applies this model to the agricultural coffee sector." },
  { term: "Crypto Bridge", definition: "Un bridge o puente cripto conecta dos blockchains distintas, permitiendo transferir activos entre ellas. Son fundamentales para la interoperabilidad en Web3.", definitionEn: "A crypto bridge connects two different blockchains, allowing assets to be transferred between them. They are essential for interoperability in Web3." },
  { term: "Círculos de confianza", termEn: "Circles of Trust", definition: "En EthicHub, los círculos de confianza son redes sociales que avalan a los originadores y prestatarios. Este sistema comunitario refuerza la fiabilidad y reduce el riesgo.", definitionEn: "At EthicHub, the circles of trust are social networks that support originators and borrowers. This community system reinforces reliability and reduces risk." },
  { term: "DAI", definition: "Stablecoin descentralizada vinculada al dólar, creada por el protocolo MakerDAO. Se usa ampliamente en DeFi por su estabilidad.", definitionEn: "A decentralized stablecoin pegged to the US dollar, created by the MakerDAO protocol. It is widely used in DeFi due to its stability." },
  { term: "DAO", definition: "Una DAO (Organización Autónoma Descentralizada) es una entidad gobernada por contratos inteligentes y sus miembros, sin una autoridad central. EthicHub evoluciona hacia un modelo DAO participativo.", definitionEn: "A DAO is a decentralized organization that operates without a central authority, governed by rules programmed into smart contracts. Its decisions are made through open voting using governance tokens." },
  { term: "DApp", definition: "Aplicación descentralizada que funciona sobre una blockchain. A diferencia de las apps tradicionales, no depende de servidores centralizados y suele utilizar smart contracts.", definitionEn: "A decentralized application that runs on a blockchain. Unlike traditional apps, it does not rely on centralized servers and typically uses smart contracts." },
  { term: "DeFi", definition: "DeFi (Finanzas Descentralizadas) engloba servicios financieros basados en blockchain que operan sin intermediarios tradicionales. Incluye préstamos, staking, intercambios y más.", definitionEn: "An ecosystem of open, decentralized, and accessible financial products that operate on blockchain without intermediaries. EthicHub is an example of DeFi applied to social and agricultural impact." },
  { term: "Deforestación", termEn: "Deforestation", definition: "La deforestación es la pérdida de áreas boscosas, causada en gran parte por prácticas agrícolas industriales. EthicHub impulsa cultivos regenerativos que ayudan a frenar este problema.", definitionEn: "Deforestation is the loss of forested areas, largely caused by industrial agricultural practices. EthicHub promotes regenerative farming that helps slow down this problem." },
  { term: "Desbancalizado", termEn: "Unbanked", definition: "Término utilizado para describir a personas que no tienen acceso a servicios financieros tradicionales. EthicHub trabaja para ofrecer alternativas sostenibles a comunidades desbancalizadas.", definitionEn: "A term used to describe people who do not have access to traditional financial services. EthicHub works to offer sustainable alternatives to unbanked communities." },
  { term: "Descentralización", termEn: "Decentralization", definition: "Principio clave en blockchain donde el poder y la toma de decisiones se distribuyen entre múltiples nodos o actores. Favorece la transparencia, seguridad y resistencia a la censura.", definitionEn: "A key principle in blockchain where power and decision-making are distributed among multiple nodes or actors. It promotes transparency, security, and resistance to censorship." },
  { term: "Descentralizado", termEn: "Decentralized", definition: "Se refiere a cualquier sistema o proceso que no depende de una entidad central, sino que está distribuido entre muchos participantes. EthicHub promueve un modelo financiero descentralizado para la inclusión rural.", definitionEn: "It refers to any system or process that does not rely on a central entity, but is instead distributed among many participants. EthicHub promotes a decentralized financial model for rural inclusion." },
  { term: "Equity", definition: "Hace referencia a la participación en el capital de una empresa. En startups, se traduce como acciones o participaciones que pueden revalorizarse con el crecimiento del proyecto.", definitionEn: "It refers to ownership in a company. In startups, it translates into shares or equity that can increase in value as the project grows." },
  { term: "Ethereum", definition: "Ethereum es una plataforma blockchain que permite ejecutar contratos inteligentes y aplicaciones descentralizadas (dApps). Es la base de muchos proyectos DeFi, incluido EthicHub.", definitionEn: "Ethereum is an open-source blockchain network that enables the execution of smart contracts and DApps. It is the foundational infrastructure for many DeFi projects, including those of EthicHub." },
  { term: "Ethichubbers", definition: "Miembros de la comunidad de EthicHub que participan como inversores, avalistas, originadores o colaboradores. Comparten valores de sostenibilidad, inclusión y finanzas éticas.", definitionEn: "Members of the EthicHub community who participate as investors, guarantors, originators, or collaborators. They share values of sustainability, inclusion, and ethical finance." },
  { term: "ETHIX", definition: "ETHIX es el token nativo de EthicHub. Sirve para avalar préstamos, participar en la gobernanza y generar recompensas en el ecosistema de inversión de impacto.", definitionEn: "ETHIX is the EthicHub impact token, used to secure agricultural loans and earn participation rewards. Its value is not only financial, but also social and regenerative." },
  { term: "Exchange", definition: "Plataforma que permite comprar, vender o intercambiar criptomonedas. Pueden ser centralizados o descentralizados.", definitionEn: "A platform that allows users to buy, sell, or exchange cryptocurrencies. These can be centralized or decentralized." },
  { term: "Exchange Centralizado (CEX)", termEn: "Centralized Exchange (CEX)", definition: "Plataforma de intercambio gestionada por una entidad que actúa como intermediaria. Ofrece facilidad de uso, pero requiere confiar en un tercero.", definitionEn: "An exchange platform managed by an entity that acts as an intermediary. It offers ease of use but requires trusting a third party." },
  { term: "Exchange Descentralizado (DEX)", termEn: "Decentralized Exchange (DEX)", definition: "Plataforma de intercambio que funciona sin intermediarios, mediante smart contracts. Los usuarios mantienen el control total de sus fondos.", definitionEn: "An exchange platform that operates without intermediaries, using smart contracts. Users retain full control of their funds." },
  { term: "Exclusión financiera", termEn: "Financial Exclusion", definition: "Situación en la que personas o comunidades no tienen acceso a servicios financieros básicos como préstamos, ahorro o seguros. EthicHub combate esta exclusión mediante tecnología y colaboración.", definitionEn: "A situation in which individuals or communities do not have access to basic financial services such as loans, savings, or insurance. EthicHub combats this exclusion through technology and collaboration." },
  { term: "FOMO", definition: "Miedo a quedarse fuera de una oportunidad de inversión o tendencia. Es común en mercados volátiles como el de criptomonedas y puede llevar a decisiones impulsivas.", definitionEn: "Fear of missing out on an investment opportunity or trend. It is common in volatile markets like cryptocurrency and can lead to impulsive decisions." },
  { term: "Farcaster", definition: "Protocolo descentralizado de redes sociales Web3, basado en identidad digital y control del usuario. Permite crear plataformas donde los datos pertenecen a las personas.", definitionEn: "A decentralized Web3 social-networking protocol based on digital identity and user control. It enables the creation of platforms where people retain ownership of their data." },
  { term: "Fee", definition: "Tarifa que se paga por utilizar un servicio blockchain, como transferencias o ejecución de contratos. Su valor varía según la red y su congestión.", definitionEn: "A fee paid for using a blockchain service, such as transfers or contract execution. Its value varies depending on the network and its congestion." },
  { term: "Fiat", termEn: "Fiat money", definition: "Moneda emitida por un gobierno (como el euro, dólar o peso) y no respaldada por un activo físico. En cripto se usa como referencia para stablecoins y valor de inversión.", definitionEn: "Currency issued by a government (such as the euro, dollar, or peso) and not backed by a physical asset. In crypto, it is used as a reference for stablecoins and investment value." },
  { term: "Fintech", definition: "Combinación de \"financial\" y \"technology\". Son empresas que usan tecnología para ofrecer servicios financieros innovadores. EthicHub es un claro ejemplo de fintech con impacto social.", definitionEn: "Combination of \"financial\" and \"technology\". They are companies that use technology to provide innovative financial services. EthicHub is a clear example of fintech with social impact." },
  { term: "Gas", definition: "El gas es la unidad que mide el coste computacional de ejecutar operaciones en una blockchain como Ethereum. Cada transacción o contrato inteligente necesita gas para procesarse.", definitionEn: "Gas is the unit that measures the computational cost of executing operations on a blockchain such as Ethereum. Every transaction or smart contract needs gas to be processed." },
  { term: "GitHub", definition: "Plataforma colaborativa de desarrollo de software donde los proyectos Web3 y blockchain publican su código abierto. EthicHub comparte allí sus contratos inteligentes para asegurar transparencia.", definitionEn: "Collaborative software development platform where Web3 and blockchain projects publish their open source. EthicHub shares its smart contracts there to ensure transparency." },
  { term: "Hash", definition: "Un hash es una secuencia alfanumérica que representa datos cifrados, generada por una función matemática. Se usa para asegurar integridad y autenticidad en blockchain.", definitionEn: "A hash is an alphanumeric sequence that represents encrypted data, generated by a mathematical function. It is used to ensure integrity and authenticity in blockchain." },
  { term: "Heifer International", definition: "Organización sin ánimo de lucro que trabaja para erradicar el hambre y la pobreza. Colabora con EthicHub en iniciativas agrícolas con impacto social.", definitionEn: "Non-profit organization that works to eradicate hunger and poverty. Collaborate with EthicHub on agricultural initiatives with a social impact." },
  { term: "IA (Inteligencia Artificial)", termEn: "AI (Artificial Intelligence)", definition: "Tecnología que permite a las máquinas aprender y tomar decisiones. En Web3, se combina con blockchain para automatizar procesos, análisis de datos y riesgo crediticio.", definitionEn: "Technology that allows machines to learn and make decisions. In Web3, it is combined with blockchain to automate processes, data analysis and credit risk." },
  { term: "Impago", termEn: "Default", definition: "Situación en la que un prestatario no devuelve el préstamo en el plazo establecido. En EthicHub, los avales colectivos ayudan a cubrir estos eventos, protegiendo al inversor.", definitionEn: "A situation in which a borrower does not repay a loan within the agreed time frame. In EthicHub, collective collateral helps cover these events, protecting the investor." },
  { term: "Inclusión financiera", termEn: "Financial Inclusion", definition: "Acceso equitativo a servicios financieros como crédito, ahorro y seguros. Es uno de los principales objetivos de EthicHub con su modelo DeFi.", definitionEn: "Equitable access to financial services such as credit, savings, and insurance. It is one of EthicHub's main goals with its DeFi model." },
  { term: "Interés", termEn: "Interest", definition: "El interés es el porcentaje de ganancia que se obtiene al prestar dinero o invertir capital. En EthicHub, los inversores reciben un interés por apoyar a agricultores.", definitionEn: "Yield is the percentage of profit earned by lending money or investing capital. In EthicHub, investors receive interest for supporting farmers." },
  { term: "Interés continuo", termEn: "Continuous interest", definition: "Modelo de cálculo de interés que se aplica constantemente sobre el capital invertido, generando crecimiento exponencial. Se utiliza en algunas plataformas DeFi.", definitionEn: "An interest calculation model that is applied constantly to the invested capital, generating exponential growth. It is used in some DeFi platforms." },
  { term: "Inversores", termEn: "Investors", definition: "Personas o entidades que destinan capital con la expectativa de obtener un rendimiento. En EthicHub, los inversores también generan impacto positivo al financiar agricultura regenerativa.", definitionEn: "Individuals or entities that allocate capital with the expectation of earning a return. In EthicHub, investors also generate positive impact by financing regenerative agriculture." },
  { term: "KYC (Know Your Customer)", definition: "Proceso obligatorio en muchos servicios financieros para verificar la identidad de los usuarios. En EthicHub se aplica a originadores y prestatarios para mayor seguridad.", definitionEn: "A mandatory process in many financial services to verify users' identities. At EthicHub, it is applied to originators and borrowers for enhanced security." },
  { term: "Lending", definition: "Lending es el acto de prestar criptoactivos a cambio de intereses. Es una de las funciones principales del ecosistema DeFi y de EthicHub.", definitionEn: "Lending is the act of lending crypto assets in exchange for interest. It is one of the main functions of the DeFi ecosystem and of EthicHub." },
  { term: "Liquidez", termEn: "Liquidity", definition: "Capacidad de un activo para convertirse rápidamente en dinero sin perder valor. La liquidez es fundamental en exchanges y pools DeFi.", definitionEn: "The ability of an asset to be quickly converted into cash without losing value. Liquidity is essential in exchanges and DeFi pools." },
  { term: "Liquidity Mining", definition: "Técnica de DeFi que recompensa a los usuarios por aportar liquidez a un protocolo. Se reciben tokens a cambio del capital aportado.", definitionEn: "DeFi technique that rewards users for providing liquidity to a protocol. Tokens are received in exchange for the capital contributed." },
  { term: "Liquidity Pool", definition: "Fondo común de tokens bloqueados en un contrato inteligente para facilitar operaciones de intercambio o préstamos. Son esenciales en exchanges descentralizados y plataformas DeFi.", definitionEn: "A shared pool of tokens locked in a smart contract to facilitate exchange operations or loans. They are essential in decentralized exchanges and DeFi platforms." },
  { term: "Líneas de crédito", termEn: "Credit Lines", definition: "Acceso preaprobado a financiación hasta un límite definido. En EthicHub, se otorgan líneas de crédito comunitarias a originadores agrícolas de café.", definitionEn: "Pre-approved access to financing up to a defined limit. At EthicHub, community credit lines are granted to agricultural originators in the coffee sector." },
  { term: "Lógica tokenómica", termEn: "Tokenomic logic", definition: "Conjunto de reglas que determinan la emisión, distribución y uso de un token dentro de un ecosistema. En EthicHub, la lógica tokenómica de ETHIX está pensada para alinear incentivos y proteger el impacto.", definitionEn: "A set of rules that determine the issuance, distribution, and use of a token within an ecosystem. At EthicHub, the tokenomics of ETHIX are designed to align incentives and protect impact." },
  { term: "Mainnet", definition: "La mainnet es la red principal de una blockchain donde las transacciones son reales. Es el entorno en el que los proyectos operan fuera de pruebas (testnet).", definitionEn: "The mainnet is the primary network of a blockchain where transactions are real. It is the environment where projects operate outside of testing (testnet)." },
  { term: "Master Private Key", definition: "Clave maestra que puede generar múltiples claves privadas derivadas. Su pérdida compromete todo el acceso a una wallet jerárquica.", definitionEn: "Master key that can generate multiple derived private keys. Your loss compromises all access to a hierarchical wallet." },
  { term: "Master Public Key", definition: "Clave pública maestra que permite generar múltiples direcciones públicas sin exponer la clave privada. Usada comúnmente en carteras HD (determinísticas jerárquicas).", definitionEn: "Master public key that allows you to generate multiple public addresses without exposing the private key. Commonly used in HD (hierarchical deterministic) portfolios." },
  { term: "MetaMask", definition: "MetaMask es una wallet digital que funciona como extensión de navegador y app móvil. Permite almacenar tokens, firmar transacciones y conectarse con DApps en Ethereum y otras redes compatibles.", definitionEn: "MetaMask is a digital wallet that works as a browser extension and mobile app. It allows users to store tokens, sign transactions, and connect with DApps on Ethereum and other compatible networks." },
  { term: "Metaverso", termEn: "Metaverse", definition: "Espacio digital inmersivo y descentralizado donde los usuarios interactúan a través de avatares. Se combina con blockchain, NFTs y economía virtual.", definitionEn: "An immersive and decentralized digital space where users interact through avatars. It combines blockchain, NFTs, and virtual economy." },
  { term: "MiCA (Markets in Crypto Assets)", definition: "Regulación europea que busca establecer un marco legal para el uso, emisión y comercialización de criptoactivos. Afecta a emisores de stablecoins, exchanges y plataformas DeFi.", definitionEn: "European regulation that aims to establish a legal framework for the use, issuance, and trading of cryptoassets. It affects stablecoin issuers, exchanges, and DeFi platforms." },
  { term: "Minería", termEn: "Mining", definition: "Proceso mediante el cual se validan transacciones y se crean nuevos bloques en ciertas blockchains (como Bitcoin), usando poder computacional. Requiere gran consumo energético.", definitionEn: "The process by which transactions are validated and new blocks are created on certain blockchains (such as Bitcoin), using computational power. It requires significant energy consumption." },
  { term: "Modelo tokenómico", termEn: "Tokenomic model", definition: "Estructura que define el propósito, utilidad, emisión y distribución de un token en un ecosistema. Un buen modelo tokenómico asegura sostenibilidad y crecimiento de un ecosistema.", definitionEn: "A structure that defines the purpose, utility, issuance, and distribution of a token within an ecosystem. A well-designed tokenomic model ensures sustainability and growth of an ecosystem." },
  { term: "NFT", definition: "Token no fungible, único e irrepetible, que representa activos digitales o físicos con propiedad verificable en blockchain. Se usa en arte digital, música, videojuegos y más.", definitionEn: "A non-fungible token, unique and unrepeatable, that represents digital or physical assets with verifiable ownership on the blockchain. It is used in digital art, music, video games, and more." },
  { term: "Nodo", termEn: "Node", definition: "Dispositivo o computadora que participa en una red blockchain validando transacciones y almacenando copias del libro contable. Su distribución garantiza descentralización.", definitionEn: "A device or computer that participates in a blockchain network by validating transactions and storing copies of the ledger. Its distribution ensures decentralization." },
  { term: "ODS (Objetivos de Desarrollo Sostenible)", termEn: "SDG (Sustainable Development Goals)", definition: "Agenda global de 17 objetivos impulsados por la ONU para erradicar la pobreza y proteger el planeta. EthicHub contribuye especialmente a los ODS 1, 2, 8, 9, 10, 12, 13, 15 y 17.", definitionEn: "A global agenda of 17 goals promoted by the UN to eradicate poverty and protect the planet. EthicHub contributes especially to SDGs 1, 2, 8, 9, 10, 12, 13, 15, and 17." },
  { term: "Originadores", termEn: "Originators", definition: "Actores locales de confianza en el ecosistema EthicHub que identifican, organizan y acompañan a los agricultores prestatarios. Son clave para la trazabilidad y sostenibilidad del modelo.", definitionEn: "Trusted local actors in the EthicHub ecosystem who identify, organize, and support borrower farmers. They are key to the model's traceability and sustainability." },
  { term: "Pequeños productores", termEn: "Small producers", definition: "Pequeños productores agrícolas que gestionan fincas familiares de escala reducida (entre dos y cinco hectáreas). Son los principales beneficiarios de la plataforma EthicHub.", definitionEn: "Small agricultural producers who manage family farms of a reduced scale (between two and five hectares). They are the main beneficiaries of the EthicHub platform." },
  { term: "Periodo de retiro", termEn: "Withdrawal period", definition: "Tiempo mínimo que debe pasar antes de poder retirar fondos o recompensas en una plataforma DeFi. En EthicHub puede aplicarse al staking o avales.", definitionEn: "Minimum period that must pass before funds or rewards can be withdrawn from a DeFi platform. At EthicHub, it may apply to staking or collateral." },
  { term: "Plantación Agroforestal", termEn: "Agroforestry Plantation", definition: "Sistema de cultivo que combina árboles con plantas agrícolas, generando beneficios ecológicos, económicos y sociales. EthicHub promueve este enfoque en sus proyectos regenerativos.", definitionEn: "A farming system that combines trees with agricultural crops, generating ecological, economic, and social benefits. EthicHub promotes this approach in its regenerative projects." },
  { term: "Pool de staking", termEn: "Staking pool", definition: "Agrupación de fondos de varios usuarios que se utilizan para validar transacciones o avalar proyectos. Permite participar en el staking con menor capital.", definitionEn: "A pooling of funds from multiple users that is used to validate transactions or guarantee projects. It allows participation in staking with smaller amounts of capital." },
  { term: "Prestamistas", termEn: "Lenders", definition: "Usuarios que ofrecen capital en plataformas de lending como EthicHub, recibiendo intereses a cambio. Son inversores que aportan liquidez a proyectos productivos.", definitionEn: "Users who provide capital on lending platforms like EthicHub, receiving interest in return. They are investors who supply liquidity to productive projects." },
  { term: "Prestatarios", termEn: "Borrowers", definition: "Personas o grupos que reciben un préstamo. En EthicHub, son agricultores organizados y evaluados por originadores locales.", definitionEn: "Individuals or groups who receive a loan. In EthicHub, they are farmers organized and assessed by local originators." },
  { term: "Proof of Authority (PoA)", definition: "Mecanismo de consenso donde ciertos nodos validados son responsables de generar nuevos bloques. Se basa en la reputación en lugar de poder computacional o staking.", definitionEn: "A consensus mechanism in which certain validated nodes are responsible for generating new blocks. It is based on reputation rather than computational power or staking." },
  { term: "Proof of Stake (PoS)", definition: "Sistema de validación en blockchain donde los participantes deben bloquear (stakear) tokens para validar transacciones y recibir recompensas. Consume menos energía que Proof of Work.", definitionEn: "A blockchain validation system where participants must lock (stake) tokens to validate transactions and receive rewards. It consumes less energy than Proof of Work." },
  { term: "Préstamos colectivos", termEn: "Crowd lending", definition: "Financiamiento de un proyecto mediante la suma de pequeñas aportaciones de múltiples personas. En EthicHub, esta fórmula permite apoyar a comunidades agrícolas.", definitionEn: "Financing a project through small contributions from multiple people. At EthicHub, this model allows supporting agricultural communities." },
  { term: "Pump", definition: "Subida repentina del precio de un activo, generalmente provocada por especulación o manipulación de mercado (pump & dump). Requiere atención para evitar decisiones impulsivas.", definitionEn: "A sudden surge in the price of an asset, usually caused by speculation or market manipulation (pump & dump). It requires caution to avoid impulsive decisions." },
  { term: "ReFi (Regenerative Finance)", definition: "Movimiento dentro de Web3 que promueve finanzas regenerativas: modelos económicos que restauran ecosistemas y comunidades. EthicHub es una plataforma ReFi que impulsa agricultura sostenible.", definitionEn: "A movement within Web3 that promotes regenerative finance: economic models that restore ecosystems and communities. EthicHub is a ReFi platform that drives sustainable agriculture." },
  { term: "Real World Assets (RWA)", definition: "Activos del mundo real (como bienes raíces, materias primas o café) que se representan digitalmente en blockchain mediante tokens. EthicHub tokeniza el café como un activo del mundo real.", definitionEn: "Real-world assets (such as real estate, commodities, or coffee) that are digitally represented on the blockchain through tokens. EthicHub tokenizes coffee as a real-world asset." },
  { term: "Red centralizada", termEn: "Centralized network", definition: "Estructura donde el control y la información están concentrados en una entidad o nodo único. Contrasta con las redes descentralizadas como blockchain.", definitionEn: "A structure where control and information are concentrated in a single entity or node. This contrasts with decentralized networks like blockchain." },
  { term: "Red descentralizada", termEn: "Decentralized network", definition: "Red en la que los datos y decisiones están distribuidos entre múltiples nodos independientes, sin una autoridad central. Es la base de blockchain y Web3.", definitionEn: "A network in which data and decisions are distributed among multiple independent nodes, without a central authority. It is the foundation of blockchain and Web3." },
  { term: "Red distribuida", termEn: "Distributed network", definition: "Estructura tecnológica donde el procesamiento y almacenamiento se reparte entre muchos dispositivos conectados. Todas las redes blockchain son distribuidas, pero no todas son descentralizadas.", definitionEn: "A technological structure where processing and storage are shared across many connected devices. All blockchain networks are distributed, but not all are decentralized." },
  { term: "Rendimiento", termEn: "Yield / Return", definition: "Ganancia que obtiene un inversor sobre su capital invertido. En DeFi, se expresa como APY (rendimiento porcentual anual) y puede variar según el riesgo.", definitionEn: "A gain an investor earns on their invested capital. In DeFi, it is expressed as APY (annual percentage yield) and can vary depending on the risk." },
  { term: "SCA (Specialty Coffee Association)", definition: "Organización internacional que establece estándares de calidad para el café de especialidad. Sus puntuaciones son clave en la comercialización del café que apoya EthicHub.", definitionEn: "An international organization that sets quality standards for specialty coffee. Its scores are key in the commercialization of the coffee supported by EthicHub." },
  { term: "Sistema de crédito tradicional", termEn: "Traditional credit system", definition: "Modelo financiero basado en bancos e intermediarios para otorgar préstamos. Muchas comunidades rurales quedan excluidas de este sistema.", definitionEn: "A financial model based on banks and intermediaries to grant loans. Many rural communities are excluded from this system." },
  { term: "Sostenibilidad", termEn: "Sustainability", definition: "Capacidad de un sistema para mantenerse en el tiempo sin agotar recursos. EthicHub promueve sostenibilidad social, económica y ambiental.", definitionEn: "The ability of a system to sustain itself over time without depleting resources. EthicHub promotes social, economic, and environmental sustainability." },
  { term: "Stablecoin", definition: "Criptomoneda cuyo valor está vinculado a un activo estable como el dólar o el euro. Se usa para reducir la volatilidad en transacciones y préstamos DeFi.", definitionEn: "A cryptocurrency whose value is pegged to a stable asset such as the dollar or the euro. It is used to reduce volatility in DeFi transactions and loans." },
  { term: "Stakear", termEn: "Stake", definition: "Acto de bloquear tokens en una red blockchain para apoyar su funcionamiento y obtener recompensas. En EthicHub, puedes stakear ETHIX para avalar préstamos agrícolas.", definitionEn: "The act of locking tokens on a blockchain network to support its operation and earn rewards. At EthicHub, you can stake ETHIX to guarantee agricultural loans." },
  { term: "Stakeholders", definition: "Personas o entidades con interés en el funcionamiento de un proyecto. En EthicHub, los stakeholders son inversores, agricultores, originadores y aliados estratégicos.", definitionEn: "People or entities with a vested interest in the functioning of a project. At EthicHub, stakeholders include investors, farmers, originators, and strategic partners." },
  { term: "Staking", definition: "Mecanismo de validación y recompensa en blockchain basado en el bloqueo de tokens. Favorece redes seguras y sostenibles como alternativa a la minería.", definitionEn: "A blockchain validation and reward mechanism based on locking tokens. It supports secure and sustainable networks as an alternative to mining." },
  { term: "Tasa de impago", termEn: "Default rate", definition: "Porcentaje de préstamos que no han sido devueltos en un periodo determinado. EthicHub mantiene una tasa histórica de impago cercana a 0%, gracias a su modelo de avales colectivos.", definitionEn: "The percentage of loans that have not been repaid within a given period. EthicHub maintains a historical default rate close to 0%, thanks to its collective collateral model." },
  { term: "Teoría de juegos", termEn: "Game theory", definition: "Campo de estudio que analiza decisiones estratégicas entre agentes. Aplicada en Web3 para diseñar economías tokenizadas y modelos de incentivos como el de ETHIX.", definitionEn: "A field of study that analyzes strategic decision-making among agents. Applied in Web3 to design tokenized economies and incentive models like ETHIX." },
  { term: "Token", definition: "Unidad digital con valor, creada y gestionada en una blockchain. Puede representar activos, derechos de voto o acceso a servicios.", definitionEn: "A digital unit with value, created and managed on a blockchain. It can represent assets, voting rights, or access to services." },
  { term: "Tokenización", termEn: "Tokenization", definition: "Proceso de representar activos físicos o derechos digitales mediante tokens en blockchain. EthicHub avanza hacia la tokenización del café como activo real.", definitionEn: "The process of representing physical assets or digital rights through tokens on a blockchain. EthicHub is moving toward the tokenization of coffee as a real asset." },
  { term: "Tokenomics", definition: "Diseño económico detrás de un token: su oferta, demanda, incentivos y utilidad. Un buen modelo tokenómico asegura sostenibilidad y crecimiento de un ecosistema.", definitionEn: "The economic design behind a token: its supply, demand, incentives, and utility. A solid tokenomic model ensures the sustainability and growth of an ecosystem." },
  { term: "Tostadores", termEn: "Roasters", definition: "Profesionales o empresas que transforman el café verde en café tostado para consumo. EthicHub conecta directamente a tostadores con caficultores de origen.", definitionEn: "Professionals or companies that transform green coffee into roasted coffee for consumption. EthicHub directly connects roasters with coffee growers at origin." },
  { term: "Trading", definition: "Operación de compra y venta de activos financieros, en este caso criptomonedas, con el objetivo de obtener ganancias. Puede ser manual o automatizado, a corto o largo plazo.", definitionEn: "The act of buying and selling financial assets (here, cryptocurrencies) with the goal of generating profit. It can be manual or automated, short-term or long-term." },
  { term: "Trazabilidad", termEn: "Traceability", definition: "Capacidad de seguir el recorrido de un producto desde su origen hasta el consumidor final. En EthicHub, la trazabilidad del café se garantiza a través de blockchain, asegurando transparencia, calidad y justicia comercial.", definitionEn: "The ability to track a product's journey from its origin to the final consumer. At EthicHub, coffee traceability is ensured through blockchain, guaranteeing transparency, quality, and fair trade." },
  { term: "Uniswap", definition: "Uno de los exchanges descentralizados (DEX) más utilizados del ecosistema DeFi. Permite intercambiar tokens de forma automática mediante contratos inteligentes y pools de liquidez.", definitionEn: "One of the most widely used decentralized exchanges (DEX) in the DeFi ecosystem. It allows tokens to be swapped automatically through smart contracts and liquidity pools." },
  { term: "Vested", definition: "Tokens vested son aquellos que están bloqueados durante un tiempo determinado y se liberan progresivamente. Este sistema se usa para alinear incentivos entre equipos y comunidades.", definitionEn: "Vested tokens are those locked for a specific period and released gradually. This system is used to align incentives between teams and communities." },
  { term: "Vesting", definition: "Mecanismo que define cómo y cuándo se desbloquean los tokens otorgados a usuarios, inversores o colaboradores. EthicHub aplica vesting para distribuir ETHIX de forma sostenible.", definitionEn: "A mechanism that defines how and when tokens granted to users, investors, or collaborators are unlocked. EthicHub applies vesting to distribute ETHIX sustainably." },
  { term: "Web3", definition: "Evolución de internet basada en blockchain, donde los usuarios tienen el control de sus datos, identidad y activos. EthicHub es parte activa del ecosistema Web3 con una propuesta de impacto real.", definitionEn: "An evolution of the internet based on blockchain, where users have control of their data, identity, and assets. EthicHub is an active part of the Web3 ecosystem with a real impact proposal." },
  { term: "Whitepapers", definition: "Documentos técnicos que explican el funcionamiento, objetivos y modelo económico de un proyecto cripto. Son clave para evaluar la viabilidad de iniciativas en Web3 y DeFi.", definitionEn: "Technical documents that explain the operation, objectives and economic model of a crypto project. They are key to evaluating the viability of Web3 and DeFi initiatives." },
  { term: "Yield Farming", definition: "Estrategia de inversión en DeFi que consiste en mover fondos entre plataformas para maximizar rendimientos. Implica riesgos altos y requiere conocimiento técnico.", definitionEn: "DeFi investment strategy that involves moving funds between platforms to maximize returns. It involves high risks and requires technical knowledge." },
]

export default function GlossaryContent() {
  const t = useTranslations("glossary")
  const locale = useLocale()
  const [searchQuery, setSearchQuery] = useState("")

  const filteredTerms = useMemo(() => {
    if (!searchQuery.trim()) return glossaryTerms
    
    const normalize = (str: string) =>
      str.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    
    const query = normalize(searchQuery)
    return glossaryTerms.filter((item) => {
      const term = locale === "en" && item.termEn ? item.termEn : item.term
      return normalize(term).includes(query)
    })
  }, [searchQuery, locale])

  const getTermDisplay = (item: GlossaryTerm) => {
    return locale === "en" && item.termEn ? item.termEn : item.term
  }

  const getDefinitionDisplay = (item: GlossaryTerm) => {
    return locale === "en" && item.definitionEn ? item.definitionEn : item.definition
  }

  return (
    <div className="pt-24 sm:pt-32 pb-12 sm:pb-24">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h1 className="text-4xl sm:text-5xl font-bold text-foreground mb-4">{t("title")}</h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              {t("description")}
            </p>
          </div>

          <div className="relative mb-10">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
            <Input
              type="text"
              placeholder={t("searchPlaceholder")}
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10 pr-10 h-12 text-base rounded-xl bg-card border-border"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery("")}
                className="absolute right-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground hover:text-foreground transition-colors"
                aria-label={t("clearSearch")}
              >
                <X className="h-5 w-5" />
              </button>
            )}
          </div>

          {filteredTerms.length === 0 ? (
            <div className="text-center py-12">
              <p className="text-muted-foreground">
                {t("noResults")} &quot;{searchQuery}&quot;
              </p>
            </div>
          ) : (
            <div className="space-y-6">
              {filteredTerms.map((item, index) => (
                <article
                  key={index}
                  className="p-6 rounded-xl bg-card border border-border transition-colors"
                >
                  <h2 className="text-xl font-semibold text-foreground mb-2">
                    {getTermDisplay(item)}
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    {getDefinitionDisplay(item)}
                  </p>
                </article>
              ))}
            </div>
          )}

          <div className="mt-10 text-center text-sm text-muted-foreground">
            {t("showing")} {filteredTerms.length} {t("of")} {glossaryTerms.length} {t("terms")}
          </div>
        </div>
    </div>
  )
}
